export enum OfferStatusEnum {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  ARCHIVED_BY_PRO = "ARCHIVED_BY_PRO",
  ACCEPTED_THEN_ARCHIVED_BY_USER = "ACCEPTED_THEN_ARCHIVED_BY_USER",
  REJECTED_THEN_ARCHIVED_BY_USER = "REJECTED_THEN_ARCHIVED_BY_USER",
}
