export enum PhoneVerificationStatusEnum {
  APPROVED = "APPROVED",
  PENDING = "PENDING",
  MAX_ATTEMPTS_REACHED = "MAX_ATTEMPTS_REACHED",
  EXPIRED = "EXPIRED",
  CANCELED = "CANCELED",
  INVALID_CODE = "INVALID_CODE",
  ALREADY_VERIFIED = "ALREADY_VERIFIED",
}