export enum ProfessionStatusEnum {
  STUDENT = "STUDENT",
  INTERIM = "INTERIM",
  CDD = "CDD",
  CDI = "CDI",
  INDEPENDANT = "INDEPENDANT",
  LIBERAL = "LIBERAL",
  COMPANY_DIRECTOR = "COMPANY_DIRECTOR",
  RETIRED = "RETIRED",
  JOB_SEEKER = "JOB_SEEKER",
  INACTIVE = "INACTIVE",
  DONT_WANT_TO_SAY = "DONT_WANT_TO_SAY",
}
