export enum ProjectNeedEnum {
  WEALTH_ASSESSMENT = "WEALTH_ASSESSMENT",
  OPTIMIZE_SAVINGS = "OPTIMIZE_SAVINGS",
  INVEST_IN_STOCK_EXCHANGE = "INVEST_IN_STOCK_EXCHANGE",
  INVEST_IN_REAL_ESTATE = "INVEST_IN_REAL_ESTATE",
  PREPARE_RETIREMENT = "PREPARE_RETIREMENT",
  PASS_ON_TO_DESCENDANTS = "PASS_ON_TO_DESCENDANTS",
  TAX_OPTIMIZATION = "TAX_OPTIMIZATION",
  SPECIFIC_PRODUCT = "SPECIFIC_PRODUCT",
  OTHER = "OTHER",
}
