export enum ProjectNeedEnum {
  WEALTH_ASSESSMENT = "WEALTH_ASSESSMENT",
  INVEST_IN_STOCK_EXCHANGE = "INVEST_IN_STOCK_EXCHANGE",
  PREPARE_RETIREMENT = "PREPARE_RETIREMENT",
  TAX_OPTIMIZATION = "TAX_OPTIMIZATION",
  OPTIMIZE_SAVINGS = "OPTIMIZE_SAVINGS",
  PASS_ON_TO_DESCENDANTS = "PASS_ON_TO_DESCENDANTS",
  DIVERSIFY_ASSETS = "DIVERSIFY_ASSETS",
  FUND_REAL_ECONOMY = "FUND_REAL_ECONOMY",
  SOCIAL_AND_ENVIRONMENTAL_INVESTMENTS = "SOCIAL_AND_ENVIRONMENTAL_INVESTMENTS",
  SAFETY_SAVINGS = "SAFETY_SAVINGS",
  SPECIFIC_PRODUCT = "SPECIFIC_PRODUCT",
}
