export interface Department {
  code: string;
  departmentName: string;
  prefectureName: string;
}

export const DepartmentsList: Department[] = [
  { code: "01", departmentName: "Ain", prefectureName: "Bourg-En-Bresse" },
  { code: "02", departmentName: "Aisne", prefectureName: "Laon" },
  { code: "03", departmentName: "Allier", prefectureName: "Moulins" },
  { code: "04", departmentName: "Alpes-De-Haute-Provence", prefectureName: "Digne-Les-Bains" },
  { code: "05", departmentName: "Hautes-Alpes", prefectureName: "Gap" },
  { code: "06", departmentName: "Alpes-Maritimes", prefectureName: "Nice" },
  { code: "07", departmentName: "Ardeche", prefectureName: "Privas" },
  { code: "08", departmentName: "Ardennes", prefectureName: "Charleville-Mezieres" },
  { code: "09", departmentName: "Ariege", prefectureName: "Foix" },
  { code: "10", departmentName: "Aube", prefectureName: "Troyes" },
  { code: "11", departmentName: "Aude", prefectureName: "Carcassonne" },
  { code: "12", departmentName: "Aveyron", prefectureName: "Rodez" },
  { code: "13", departmentName: "Bouches-Du-Rhone", prefectureName: "Marseille" },
  { code: "14", departmentName: "Calvados", prefectureName: "Caen" },
  { code: "15", departmentName: "Cantal", prefectureName: "Aurillac" },
  { code: "16", departmentName: "Charente", prefectureName: "Angouleme" },
  { code: "17", departmentName: "Charente-Maritime", prefectureName: "La rochelle" },
  { code: "18", departmentName: "Cher", prefectureName: "Bourges" },
  { code: "19", departmentName: "Correze", prefectureName: "Tulle" },
  { code: "21", departmentName: "Cote-D'Or", prefectureName: "Dijon" },
  { code: "22", departmentName: "Cotes-D'Armor", prefectureName: "Saint-Brieuc" },
  { code: "23", departmentName: "Creuse", prefectureName: "Gueret" },
  { code: "24", departmentName: "Dordogne", prefectureName: "Perigueux" },
  { code: "25", departmentName: "Doubs", prefectureName: "Besancon" },
  { code: "26", departmentName: "Drome", prefectureName: "Valence" },
  { code: "27", departmentName: "Eure", prefectureName: "Evreux" },
  { code: "28", departmentName: "Eure-Et-Loir", prefectureName: "Chartres" },
  { code: "29", departmentName: "Finistere", prefectureName: "Quimper" },
  { code: "2A", departmentName: "Corse-Du-Sud", prefectureName: "Ajaccio" },
  { code: "2B", departmentName: "Haute-Corse", prefectureName: "Bastia" },
  { code: "30", departmentName: "Gard", prefectureName: "Nimes" },
  { code: "31", departmentName: "Haute-Garonne", prefectureName: "Toulouse" },
  { code: "32", departmentName: "Gers", prefectureName: "Auch" },
  { code: "33", departmentName: "Gironde", prefectureName: "Bordeaux" },
  { code: "34", departmentName: "Herault", prefectureName: "Montpellier" },
  { code: "35", departmentName: "Ille-Et-Vilaine", prefectureName: "Rennes" },
  { code: "36", departmentName: "Indre", prefectureName: "Chateauroux" },
  { code: "37", departmentName: "Indre-Et-Loire", prefectureName: "Tours" },
  { code: "38", departmentName: "Isere", prefectureName: "Grenoble" },
  { code: "39", departmentName: "Jura", prefectureName: "Lons-Le-Saunier" },
  { code: "40", departmentName: "Landes", prefectureName: "Mont-De-Marsan" },
  { code: "41", departmentName: "Loir-Et-Cher", prefectureName: "Blois" },
  { code: "42", departmentName: "Loire", prefectureName: "Saint-Etienne" },
  { code: "43", departmentName: "Haute-Loire", prefectureName: "Le puy-En-Velay" },
  { code: "44", departmentName: "Loire-Atlantique", prefectureName: "Nantes" },
  { code: "45", departmentName: "Loiret", prefectureName: "Orleans" },
  { code: "46", departmentName: "Lot", prefectureName: "Cahors" },
  { code: "47", departmentName: "Lot-Et-Garonne", prefectureName: "Agen" },
  { code: "48", departmentName: "Lozere", prefectureName: "Mende" },
  { code: "49", departmentName: "Maine-Et-Loire", prefectureName: "Angers" },
  { code: "50", departmentName: "Manche", prefectureName: "Saint-Lo" },
  { code: "51", departmentName: "Marne", prefectureName: "Chalons-En-Champagne" },
  { code: "52", departmentName: "Haute-Marne", prefectureName: "Chaumont" },
  { code: "53", departmentName: "Mayenne", prefectureName: "Laval" },
  { code: "54", departmentName: "Meurthe-Et-Moselle", prefectureName: "Nancy" },
  { code: "55", departmentName: "Meuse", prefectureName: "Bar-Le-Duc" },
  { code: "56", departmentName: "Morbihan", prefectureName: "Vannes" },
  { code: "57", departmentName: "Moselle", prefectureName: "Metz" },
  { code: "58", departmentName: "Nievre", prefectureName: "Nevers" },
  { code: "59", departmentName: "Nord", prefectureName: "Lille" },
  { code: "60", departmentName: "Oise", prefectureName: "Beauvais" },
  { code: "61", departmentName: "Orne", prefectureName: "Alencon" },
  { code: "62", departmentName: "Pas-De-Calais", prefectureName: "Arras" },
  { code: "63", departmentName: "Puy-De-Dome", prefectureName: "Clermont-Ferrand" },
  { code: "64", departmentName: "Pyrenees-Atlantiques", prefectureName: "Pau" },
  { code: "65", departmentName: "Hautes-Pyrenees", prefectureName: "Tarbes" },
  { code: "66", departmentName: "Pyrenees-Orientales", prefectureName: "Perpignan" },
  { code: "67", departmentName: "Bas-Rhin", prefectureName: "Strasbourg" },
  { code: "68", departmentName: "Haut-Rhin", prefectureName: "Colmar" },
  { code: "69", departmentName: "Rhone", prefectureName: "Lyon" },
  { code: "70", departmentName: "Haute-Saone", prefectureName: "Vesoul" },
  { code: "71", departmentName: "Saone-Et-Loire", prefectureName: "Macon" },
  { code: "72", departmentName: "Sarthe", prefectureName: "Le mans" },
  { code: "73", departmentName: "Savoie", prefectureName: "Chambery" },
  { code: "74", departmentName: "Haute-Savoie", prefectureName: "Annecy" },
  { code: "75", departmentName: "Paris", prefectureName: "" },
  { code: "76", departmentName: "Seine-Maritime", prefectureName: "Rouen" },
  { code: "77", departmentName: "Seine-Et-Marne", prefectureName: "Melun" },
  { code: "78", departmentName: "Yvelines", prefectureName: "Versailles" },
  { code: "79", departmentName: "Deux-Sevres", prefectureName: "Niort" },
  { code: "80", departmentName: "Somme", prefectureName: "Amiens" },
  { code: "81", departmentName: "Tarn", prefectureName: "Albi" },
  { code: "82", departmentName: "Tarn-Et-Garonne", prefectureName: "Montauban" },
  { code: "83", departmentName: "Var", prefectureName: "Toulon" },
  { code: "84", departmentName: "Vaucluse", prefectureName: "Avignon" },
  { code: "85", departmentName: "Vendee", prefectureName: "La roche-Sur-Yon" },
  { code: "86", departmentName: "Vienne", prefectureName: "Poitiers" },
  { code: "87", departmentName: "Haute-Vienne", prefectureName: "Limoges" },
  { code: "88", departmentName: "Vosges", prefectureName: "Epinal" },
  { code: "89", departmentName: "Yonne", prefectureName: "Auxerre" },
  { code: "90", departmentName: "Territoire de belfort", prefectureName: "Belfort" },
  { code: "91", departmentName: "Essonne", prefectureName: "Evry" },
  { code: "92", departmentName: "Hauts-De-Seine", prefectureName: "Nanterre" },
  { code: "93", departmentName: "Seine-Saint-Denis", prefectureName: "Bobigny" },
  { code: "94", departmentName: "Val-De-Marne", prefectureName: "Creteil" },
  { code: "95", departmentName: "Val-D'Oise", prefectureName: "Pontoise" },
  { code: "97", departmentName: "Guadeloupe", prefectureName: "Basse-Terre" },
  { code: "97", departmentName: "Guyane", prefectureName: "Cayenne" },
  { code: "97", departmentName: "Martinique", prefectureName: "Fort-De-France" },
  { code: "97", departmentName: "Mayotte", prefectureName: "Dzaoudzi" },
  { code: "97", departmentName: "Reunion", prefectureName: "Saint-Denis" },
];
